### ISSUE TITLE
The time of loading for the training data

### ISSUE THREAD

**Issue by SaltyFishhh** [jzyustc/MBRS#1]
Hello，Do datasets take long to load when you train models? What is the general training time?
I use the COCO2014 as the training datasets,it takes a long time to load.

**Comment by SaltyFishhh** [comment]
Besides,What is the ratio between training datasets and validation datasets?

**Comment by jzyustc** [comment]
Hello, thanks for your issue. It's just because I forget to change the loading function in the code.

In fact I load the whole dataset into the memory before training. It takes long time to load them at once, but will speed up the later training, just like a future step for **pin_memory** (you can find I store the loaded dataset in **train_dataloader** in **train.py**). 

But it seems not the normal usage of **torch.utils.data.dataset**, so I will change it back to use **__getitem__** function, before next Monday.

For the training time, it takes about 12 hours to train the model **MBRS_256_256** which embeds 256bits into a 256\*256 RGB image, with 4 2080Ti GPUs. And it will be much quicker to train for a 128*128 image.

**Comment by jzyustc** [comment]
In my implementation, I used 5000 images for validation because it didn't take much time. You can change it as you like.

**Comment by jzyustc** [comment]
Code updated. Closed.
